name: Upload Release Artifacts

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} build/libs/Spikedog.jar &
          gh release upload ${{ github.ref_name }} info-module/build/libs/info-module.jar &
          gh release upload ${{ github.ref_name }} reload-module/build/libs/reload-module.jar &
      - name: Upload to DiruptioPublic Maven repository
        env:
          DIRUPTIO_MAVEN_USERNAME: ${{ secrets.DIRUPTIO_MAVEN_USERNAME }}
          DIRUPTIO_MAVEN_PASSWORD: ${{ secrets.DIRUPTIO_MAVEN_PASSWORD }}
        run: ./gradlew publish --stacktrace
      - name: Create Diruptio projects version (pre-release)
        if: 'github.event.release.prerelease'
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" -d "{"project":"spikedog","name":"${{ github.ref_name }}","tags":["pre-release"],"gitCommit":"${{ github.sha }}"}" "https://api.diruptio.de/project/version/create"
      - name: Create Diruptio projects version (release)
        if: '!github.event.release.prerelease'
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" -d "{"project":"spikedog","name":"${{ github.ref_name }}","tags":["release"],"gitCommit":"${{ github.sha }}"}" "https://api.diruptio.de/project/version/create"
      - name: Upload to Diruptio projects
        run: |
          cat build/libs/Spikedog.jar | curl -X POST -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" --data @- "https://api.diruptio.de/project/version/upload?project=spikedog&version=${{ github.ref_name }}&file=Spikedog.jar"
          cat info-module/build/libs/info-module.jar | curl -X POST -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" --data @- "https://api.diruptio.de/project/version/upload?project=spikedog&version=${{ github.ref_name }}&file=info-module.jar"
          cat reload-module/build/libs/reload-module.jar | curl -X POST -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" --data @- "https://api.diruptio.de/project/version/upload?project=spikedog&version=${{ github.ref_name }}&file=reload-module.jar"